//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDeliveryApp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFood
    {
        public int Id { get; set; }
        public int OId { get; set; }
        public int FId { get; set; }
        public decimal FPrice { get; set; }
        public int FQty { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Order Order { get; set; }
    }
}
